### PR TITLE
Format version

### PR DESCRIPTION
**Pull request by SimonRubenDrauz**
bug detected

### CODE REVIEW

**Review by dlohmeier — COMMENTED** [review]
What errors would occur there? I didn't quite get why the previous version was wrong...

**Comment by SimonRubenDrauz** [comment]
> What errors would occur there? I didn't quite get why the previous version was wrong...

The reason is the following. As soon as you load a network, an empty network is created and the different parameter are passed afterwards. If you have a net, which doesn't have the attribute format_version, it is not overwritten. Thus, the current format_version remains and therefore convert_format won't be applied. The reason, why the tests passed before, was a typo: __format_version__ instead of format_version. 

Do you have any other idea what might be a better way to solve that problem.

**Comment by dlohmeier** [comment]
That's indeed an issue, and I think that we should rather try to make adaptions to the `from_json()` part. Does it appear in other formats as well? The correct behavior, whether with or without `convert_format()`, should be that we load the old net and if format_version doesn't exist, we replace this value with the saved net version. But this has to be done before the `convert_format()` task, of course.

**Comment by SimonRubenDrauz** [comment]
adapted it accordingly. Please check it out if you agree with the solution.

**Review by dlohmeier — APPROVED** [review]
Looks good!

**Pull request merged**
