### PR TITLE
pipeflow exception is raised if colebrook algorithm does not converge

### PR DESCRIPTION
**Pull request by dlohmeier**

### CODE REVIEW

**Comment by dlohmeier** [comment]
This should solve Issue #211.

**Review by dcronbach — APPROVED** [review]
Looks good. The import statement in derivative_toolbox in line 48 looks a little bit odd as we usually put them on top of each module. But you probably placed it there because the import only happens because of the exception.

**Comment by dlohmeier** [comment]
Yes, I would prefer a top-level import as well, but that would lead to a circular import that cannot be resolved. I think there should be another way to handle this problem, but I am not yet sure how. I mentioned this problem in issue #232.

**Comment by dlohmeier** [comment]
I added a TODO statement there.

**Pull request merged**
