### PR TITLE
Fix/numpy release

### PR DESCRIPTION
**Pull request by mfranz13**
Numpy released its 2.0.0 version on June 16th. The release contains some brekaing changes that are all described in the [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html). A lot of members of the np. namespace have been deprecated, removed or moved. Most notably for us, they changed that previously capitalized variable names like np.NaN or np.Inf now consist entirely of lowercase letters.

### CODE REVIEW

**Review by EPrade — APPROVED** [review]

**Comment by dlohmeier** [comment]
Thanks for making adjustments for new numpy releases. Can you provide a hint what has been changed and what is necessary to adapt?

**Comment by mfranz13** [comment]
@dlohmeier I added a brief explanation in the description.

**Comment by dlohmeier** [comment]
Thanks for the description. What I find interesting is that they recommend ruff usage with the respective linting rule.

**Comment by mfranz13** [comment]
I implemented the changes with ruff as they are describing it. Unfortunately i had to fix all imports of Inf myself because they did not get detected.

**Comment by mfranz13** [comment]
FYI: Changes for pandapower are already on their way and should be released today or tomorrow

**Comment by EPrade** [comment]
Changes in pandapower have been merged on master. Now all checks are passing. Should we merge this PR?

**Pull request merged**
